export function buildPrompt(briefingData) {
  const b = briefingData;
  
  return `Você é um consultor de branding sênior da Stark Marketing (agência de estética/cirurgia plástica). Analise o briefing e retorne APENAS um JSON válido, sem markdown, sem texto extra.

Briefing: empresa="${b.nomeEmpresa}", segmento="${b.segmento}", descrição="${b.descricaoEmpresa}", logo="${b.statusLogo}", público="${b.faixaEtaria} ${b.generoPredominante} ${b.estiloVida}", tom=${JSON.stringify(b.tomDeVoz)}, adjetivos="${b.adjetivos}", paletas=${JSON.stringify(b.paletasSelecionadas)}, tipografia=${JSON.stringify(b.estilosFonte)}, layout="${b.layoutLP}", seções=${JSON.stringify(b.secoesLP)}, CTA="${b.ctaPrincipal}", plataformas=${JSON.stringify(b.plataformas)}, frequência="${b.frequenciaPostagem}", referências="${b.referenciasVisuais}", prazo="${b.prazoEntrega}", observações="${b.observacoesExtras}"

Retorne este JSON preenchido em PT-BR:
{"diagnostico":{"sintese":"","arquetipos":{"dominante":"","dominante_justificativa":"","secundario":"","secundario_justificativa":""},"tom_de_voz":{"perfil":"","palavras_que_usa":["","","","",""],"palavras_que_evita":["","","",""]},"posicionamento":"","oportunidades":["",""]},"identidade_visual":{"personalidade_visual":"","paleta":{"cor_primaria":{"nome":"","hex":"","racional":""},"cor_secundaria":{"nome":"","hex":"","racional":""},"cor_de_apoio":{"nome":"","hex":"","racional":""},"cor_neutra":{"nome":"","hex":"","racional":""}},"tipografia":{"fonte_titulo":{"nome":"","estilo":"","racional":""},"fonte_corpo":{"nome":"","estilo":"","racional":""}},"linguagem_fotografica":{"estilo_geral":"","iluminacao":"","composicao":"","paleta_fotografica":"","o_que_evitar":["",""]},"linguagem_arquetipia":{"narrativa_central":"","metaforas_visuais":["",""],"mood_palavras":["","","","",""]},"moodboard_descritivo":""},"landing_page":{"layout_recomendado":"","secoes":[{"nome":"Hero","objetivo":"","copy_sugerido":""}],"cta_principal":"","diretrizes_visuais":""},"social_media":{"plataformas_prioritarias":[],"pilares_de_conteudo":[{"nome":"","descricao":"","frequencia_sugerida":""}],"diretrizes_visuais_feed":"","tom_nas_legendas":""},"extras":{"tagline_sugestoes":["","",""],"naming_observacoes":"","proximos_passos":["","",""]}}`;
}
